--- 
title: "Courses @ CRG: Reproducible research and data analysis with Linux containers and Nextflow pipelines"

author:
  - Sarah Bonnin^[CRG, sarah.bonnin@crg.eu], Luca Cozzuto^[CRG, luca.cozzuto@crg.eu], Toni Hermoso^[CRG, toni.hermoso@crg.eu], Julia Ponomarenko^[CRG, julia.ponomarenko@crg.eu]
 
site: bookdown::Containers_Nextflow_course
output: bookdown::gitbook
documentclass: book
bibliography: [book.bib, packages.bib]
biblio-style: apalike
link-citations: yes
---


# Welcome and about the course

This slow-paced hands-on course is designed for absolute beginners who want to start using containers and Nextflow pipelines to achieve reproducibility of data analysis. <br>
Linux containers allow the storage of code and applications in an host-independent lightweight environment. They became a fast and popular way to share and deploy applications in different environments. <br>
[Nextflow](https://www.nextflow.io) is a powerful polyglot workflow language that, coupled with [Docker](https://www.docker.com/) and [Singularity](https://sylabs.io/singularity/) containers, provides a robust, scalable and reproducible way to run computational pipelines.



## Meet the organizers and instructors

Check the [padlet](https://padlet.com/annasolea/nvp3rlxa0r37gud0)!

Contacts below:

* CRG Training unit:
    * [Damjana](mailto:damjana.kastelic@crg.eu)
    * [Anna](mailto:anna.sole@crg.eu)

* Main speakers:
    * [Toni](mailto:toni.hermoso@crg.eu) (Containers)
    * [Luca](mailto:luca.cozzuto@crg.eu) (Nextflow)

* Instructors/helper:
    * [Emilio](mailto:emilio.palumbo@crg.eu)
    * [Jose](mailto:joseantonio.espinosa@crg.eu)
    * [Alessio](mailto:alessio.vignoli@crg.eu)
    * [Athanasios](mailto:athanasios.baltzis@crg.eu)
    * [Leila](mailto:leila.mansouri@crg.eu)
    * [Edgar](mailto:edgar.garriga@crg.eu)
    * [Julia](mailto:julia.ponomarenko@crg.eu)
    * [Sarah](mailto:sarah.bonnin@crg.eu)


## About the course

### Outline

The 4-day Containers and Nextflow course will train participants to use and build Docker and Singularity containers and Nextflow pipelines.
It is designed to provide trainees with short and frequent hands-on sessions, while keeping theoretical sessions to a minimum.

The course will be fully virtual via the [Zoom](https://zoom.us/) platform.

Trainees will work in a dedicated [AWS environment](https://en.wikipedia.org/wiki/AWS).


### Learning objectives

About Linux containers:

- Locate and fetch Docker/Singularity images from dedicated repositories.
- Execute/Run a Docker/Singularity container from the command line.
- Build Docker container from an existing recipe.
- Design/Write a Docker recipe.
- Convert Docker to Singularity image.

About Nextflow:

- Locate and fetch Nextflow pipelines from dedicated repositories.
- Execute/Run a Nextflow pipeline.
- Describe and explain Nextflow's basic concepts.
- Test and modify a Nextflow pipeline.
- Implement short blocks of code into a Nextflow pipeline.
- Develop a Nextflow pipeline from scratch.
- Run pipeline in diverse computational environments (local, HPC, cloud )

### Prerequisite / technical requirements

#### Prerequisite

* Being comfortable working with the CLI (command-line interface) in a Linux-based environment. 
* Applicants are not expected to have used neither Linux containers nor Nextflow workflows before.

#### Technical requirements

* You should have access to a terminal on your machine to access the cloud via ssh:
    * on Linux and Mac operating systems it is there by default.
    * on Windows, you could install a [Windows terminal](https://www.microsoft.com/en-us/p/windows-terminal/9n0dx20hk701?activetab=pivot:overviewtab) or an application like [putty](https://www.putty.org/).
<br>
If you are not familiar with the **ssh** protocol, you can learn about it <a href="https://www.hostinger.com/tutorials/ssh-tutorial-how-does-ssh-work" target="_blank">here</a>.
<br>
* You should also be able to use a **command-line/screen-oriented text editor** (such as nano or vi/vim) or to be able to use an editor able to connect remotely like Visual studio, emacs or bbedit. If you are not sure what text editor to use, we recommend that you <a href="https://wiki.gentoo.org/wiki/Nano/Basics_Guide" target="_blank">learn the basics of "nano"</a>.
<br>
* During the course, we will use the [**Slack**](https://slack.com) platform for discussion and troubleshooting. You can either [install the Slack app](https://slack.com/intl/en-es/help/categories/360000049043#download-slack) before the course, or you will be able to access Slack from a web browser.
<br>
* We also encourage you to create a [**Github account**](https://github.com/join) and an associated [**Docker hub account**](https://hub.docker.com/signup).



### Dates, time, location

- Dates: May 2021: 
 - Containers: Monday 3rd, Tuesday 4th
 - Nextflow: Monday 10th, Tuesday 11th
- Time: 9:30-17:30:
  - Morning coffee break: 11:00-11:30am
  - Lunch break: 1pm-2pm 
  - Afternoon coffee break: 3:30-4:00pm
- Location: virtual, via Zoom.

You can find all information in the dedicated course page of the [Moodle platform](https://moodle.crg.eu).

## Program

### May 3-4: Containers

#### Day 1: Docker

* Containers: introduction and history.
* Docker hub: find existing containers.
* Fetch (and build) an image from public registries (Docker Hub, Quay.io, etc.)
 * Discovery of different relevant base images
* Run Docker container based on an existing image (also run it interactively).
* Build an image from an existing recipe:
  * Explain sections and keywords.
  * Build options (e.g. cache or build variables).
* Write a Docker recipe and build an image from it.

#### Day 2: Docker + Singularity

* Docker:
  * Work with volumes and ports.
  * Upload image to registries.
* Singularity:
  * Singularity versus Docker.
    * Differences, pros and cons for each system.
  * Fetch (and build) Singularity images.
    * Build from existing public registries.
    * Build from local Docker instances.
  * Run Singularity container (interactively).
  * Understanding and working with volumes.
  * Singularity build recipes.
  * Advanced features: services, etc.

### May 10-11: Nextflow

#### Day 3: Understand the code, run, modify

- Introduction to Nextflow
- Scripting
- Basic concepts:
  - Channels, processes and workflows
- The work folder and its structure
- The log file
- Resuming pipelines

#### Day 4: Write and share

- Decoupling configuration and main script
- Run Nextflow with containers
- Run Nextflow in a computing cluster (e.g. HPC)
  - Definition of computing requirements and queues
  - Profiles
- Modules, subworkflows and reuse of the code
- Share Nextflow pipelines and good practices 


